{
  "formatVersion": "1.1",
  "component": {
    "group": "me.sizableshrimp.parchmenttest",
    "module": "ForgeGradle",
    "version": "5.0.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeGradle-5.0.48.jar",
          "url": "ForgeGradle-5.0.48.jar",
          "size": 403855,
          "sha512": "9663338022bd67aedc9fb0f92d4a5fa87bd1ead3ef7ccb3492b41d7ff94398174b841f6fd53b3422250f2cde173d1f3418c7f6c354d9618ee97f0195c4f6328e",
          "sha256": "14afe2a07bf7757d9cebbf9ece0adfc474947e4ec07b0db2a70cdc783d3e4612",
          "sha1": "b1665107836242d2327391cd557d1f5fbf0f7856",
          "md5": "30fd5c5779f7d9d3c775c972b50b5eb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "requires": "3.0.8"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.6.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.7"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ForgeGradle-5.0.48.jar",
          "url": "ForgeGradle-5.0.48.jar",
          "size": 403855,
          "sha512": "9663338022bd67aedc9fb0f92d4a5fa87bd1ead3ef7ccb3492b41d7ff94398174b841f6fd53b3422250f2cde173d1f3418c7f6c354d9618ee97f0195c4f6328e",
          "sha256": "14afe2a07bf7757d9cebbf9ece0adfc474947e4ec07b0db2a70cdc783d3e4612",
          "sha1": "b1665107836242d2327391cd557d1f5fbf0f7856",
          "md5": "30fd5c5779f7d9d3c775c972b50b5eb2"
        }
      ]
    }
  ]
}
