{
  "formatVersion": "1.1",
  "component": {
    "group": "me.sizableshrimp.parchmenttest",
    "module": "ForgeGradle",
    "version": "5.0.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeGradle-5.0.48.jar",
          "url": "ForgeGradle-5.0.48.jar",
          "size": 403855,
          "sha512": "454e289899b7dcaf590ef4465a0cd1b400134f2f60ed6ac0e44fc2c6c12325f85431c9ea87bc202d73e62383b4001f9b327274311c866e9e2f572f85ad5061b8",
          "sha256": "e2e5610b8798bd2b57ef495c672af9d2947b5084f50ddce3f8ff26ee9418110c",
          "sha1": "61f35522171788d0585b5025d4e984e0da1235c3",
          "md5": "cae615e36023044d4a98ddcad5608d46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "requires": "3.0.8"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.6.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.7"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ForgeGradle-5.0.48.jar",
          "url": "ForgeGradle-5.0.48.jar",
          "size": 403855,
          "sha512": "454e289899b7dcaf590ef4465a0cd1b400134f2f60ed6ac0e44fc2c6c12325f85431c9ea87bc202d73e62383b4001f9b327274311c866e9e2f572f85ad5061b8",
          "sha256": "e2e5610b8798bd2b57ef495c672af9d2947b5084f50ddce3f8ff26ee9418110c",
          "sha1": "61f35522171788d0585b5025d4e984e0da1235c3",
          "md5": "cae615e36023044d4a98ddcad5608d46"
        }
      ]
    }
  ]
}
