{
  "formatVersion": "1.1",
  "component": {
    "group": "me.sizableshrimp.parchmenttest",
    "module": "ForgeGradle",
    "version": "4.1.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "wwwxscqne5f65campuze4ucpw4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeGradle-4.1.22.jar",
          "url": "ForgeGradle-4.1.22.jar",
          "size": 401114,
          "sha512": "298961f62a70ef354b78e34a20c5c2f441a29eb861a72f6fd7f37fc76e9adc52c8806a3d6f862ad9d9e1695b008e10a7899006127eabca93fe92784d198fde45",
          "sha256": "2560b384d51f102ae5b35d68b41c60b302dc612b5d62bb4cd9df533044611e70",
          "sha1": "b348e88bb5db69332dfe3d0fdce10ae5c803534d",
          "md5": "ff4b65a524c2b963a236df70efcab21b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.nothome",
          "module": "javaxdelta",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "requires": "2.0.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.6.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.5"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ForgeGradle-4.1.22.jar",
          "url": "ForgeGradle-4.1.22.jar",
          "size": 401114,
          "sha512": "298961f62a70ef354b78e34a20c5c2f441a29eb861a72f6fd7f37fc76e9adc52c8806a3d6f862ad9d9e1695b008e10a7899006127eabca93fe92784d198fde45",
          "sha256": "2560b384d51f102ae5b35d68b41c60b302dc612b5d62bb4cd9df533044611e70",
          "sha1": "b348e88bb5db69332dfe3d0fdce10ae5c803534d",
          "md5": "ff4b65a524c2b963a236df70efcab21b"
        }
      ]
    }
  ]
}
