{
  "formatVersion": "1.1",
  "component": {
    "group": "me.sizableshrimp.parchmenttest",
    "module": "ForgeGradle",
    "version": "5.1.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeGradle-5.1.31.jar",
          "url": "ForgeGradle-5.1.31.jar",
          "size": 414642,
          "sha512": "58e419396d0b81d6e6152cb99f91ae6db726e8158f816663caa6a782d5083610504ada8d28110f9d96e4108a776cf1606838ca91a0e341260670bb80a213ac0b",
          "sha256": "c7d6d0a4fdbd92b47dbcd5944db0dfb5468c459a65276b1c6a451d2843192190",
          "sha1": "fa979a147bd1ea4cd8a8a64c18daa38b8a38082e",
          "md5": "3b956b7471899c92f5239dca004ab250"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "requires": "3.0.8"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.6.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.7"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ForgeGradle-5.1.31.jar",
          "url": "ForgeGradle-5.1.31.jar",
          "size": 414642,
          "sha512": "58e419396d0b81d6e6152cb99f91ae6db726e8158f816663caa6a782d5083610504ada8d28110f9d96e4108a776cf1606838ca91a0e341260670bb80a213ac0b",
          "sha256": "c7d6d0a4fdbd92b47dbcd5944db0dfb5468c459a65276b1c6a451d2843192190",
          "sha1": "fa979a147bd1ea4cd8a8a64c18daa38b8a38082e",
          "md5": "3b956b7471899c92f5239dca004ab250"
        }
      ]
    }
  ]
}
