{
  "formatVersion": "1.1",
  "component": {
    "group": "me.sizableshrimp.gradle",
    "module": "ForgeGradle",
    "version": "6.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeGradle-6.0.3.jar",
          "url": "ForgeGradle-6.0.3.jar",
          "size": 488078,
          "sha512": "dd675439fe1e7f44c0f2ad7c5f820a63b7eef62fef8cbe48e54b4e95e760c8fc00fffd22d43ef8d51cf5d10c1a3cfe3ad78362d41231a4ed94263b4470ad0fae",
          "sha256": "d7674f609b5a43d7a1154bc3501c7c2f7118ebef8c437c0aa2ae3145133cc258",
          "sha1": "7c0c635ce832a818ed099393d576d2be618fa59d",
          "md5": "be12dd679a635afe74ad106af4ceb07c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "requires": "3.0.14"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.9.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.14"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.15"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.7"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ForgeGradle-6.0.3.jar",
          "url": "ForgeGradle-6.0.3.jar",
          "size": 488078,
          "sha512": "dd675439fe1e7f44c0f2ad7c5f820a63b7eef62fef8cbe48e54b4e95e760c8fc00fffd22d43ef8d51cf5d10c1a3cfe3ad78362d41231a4ed94263b4470ad0fae",
          "sha256": "d7674f609b5a43d7a1154bc3501c7c2f7118ebef8c437c0aa2ae3145133cc258",
          "sha1": "7c0c635ce832a818ed099393d576d2be618fa59d",
          "md5": "be12dd679a635afe74ad106af4ceb07c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeGradle-6.0.3-sources.jar",
          "url": "ForgeGradle-6.0.3-sources.jar",
          "size": 215222,
          "sha512": "2af3f01ebb7ca495ba5a6d4c053104da374afaccb5570dc6f3eff66b01e83cd130eaef5f6b384ed798da8f13596e4233546940b5f1976a5d2fd72097844c124e",
          "sha256": "275dbb57a441b9eeeac229d141168918f24fabd7ad2ccb46888b152246e8e93a",
          "sha1": "fb9b8df4fd513f91c9a06242a5a89fe7db5cf512",
          "md5": "17a741e12000c267a2ac59dda2944c98"
        }
      ]
    }
  ]
}
