{
  "formatVersion": "1.1",
  "component": {
    "group": "me.sizableshrimp.gradle",
    "module": "ForgeGradle",
    "version": "5.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeGradle-5.0.4.jar",
          "url": "ForgeGradle-5.0.4.jar",
          "size": 392503,
          "sha512": "231625c44adb5b0a9ce579ad73fa160b2ee3d50fb840b5a5e929adad891332921bd3fb6cbdabfddfd167e5f9f02113fb7c809f6b6f3aa6256a58535cb0547329",
          "sha256": "49a67cb0b6cfe7c7e174ed71074a7304a45c9b01972e8b58af09085abbc8c13f",
          "sha1": "9c8c9bb55fcc381bc2f2f29b725ed252c931e6f4",
          "md5": "625d65bc39bb7338a7707179898ee8af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.nothome",
          "module": "javaxdelta",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "requires": "2.0.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.6.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.5"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ForgeGradle-5.0.4.jar",
          "url": "ForgeGradle-5.0.4.jar",
          "size": 392503,
          "sha512": "231625c44adb5b0a9ce579ad73fa160b2ee3d50fb840b5a5e929adad891332921bd3fb6cbdabfddfd167e5f9f02113fb7c809f6b6f3aa6256a58535cb0547329",
          "sha256": "49a67cb0b6cfe7c7e174ed71074a7304a45c9b01972e8b58af09085abbc8c13f",
          "sha1": "9c8c9bb55fcc381bc2f2f29b725ed252c931e6f4",
          "md5": "625d65bc39bb7338a7707179898ee8af"
        }
      ]
    }
  ]
}
