{
  "formatVersion": "1.1",
  "component": {
    "group": "org.spongepowered",
    "module": "mixingradle",
    "version": "0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mixingradle-0.8-SNAPSHOT.jar",
          "url": "mixingradle-0.8-SNAPSHOT.jar",
          "size": 112223,
          "sha512": "80de5ee82625ce06c4fefa4174590ac2e00bb6f8928c8894d2d65c0193fed7a11688117c8f5f812a69d7cdd93b587a3110fb24d1fc0977a8f4b096027492beaf",
          "sha256": "0dda57a4b95857a6aa9b5c74ff8c83e4341250c66ec22ae18329c4cb5ff6bc41",
          "sha1": "8a856ed29043cdeace6c738e858b1e8331b65587",
          "md5": "8e6c3ae4e0e52d1fcc9e2e2e602e77d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "6.2"
          }
        }
      ],
      "files": [
        {
          "name": "mixingradle-0.8-SNAPSHOT.jar",
          "url": "mixingradle-0.8-SNAPSHOT.jar",
          "size": 112223,
          "sha512": "80de5ee82625ce06c4fefa4174590ac2e00bb6f8928c8894d2d65c0193fed7a11688117c8f5f812a69d7cdd93b587a3110fb24d1fc0977a8f4b096027492beaf",
          "sha256": "0dda57a4b95857a6aa9b5c74ff8c83e4341250c66ec22ae18329c4cb5ff6bc41",
          "sha1": "8a856ed29043cdeace6c738e858b1e8331b65587",
          "md5": "8e6c3ae4e0e52d1fcc9e2e2e602e77d2"
        }
      ]
    }
  ]
}
