{
  "formatVersion": "1.1",
  "component": {
    "group": "me.sizableshrimp.gradle",
    "module": "ForgeGradle",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeGradle-6.0.0.jar",
          "url": "ForgeGradle-6.0.0.jar",
          "size": 500007,
          "sha512": "46f804eab2df94f43c0e2480e43a0186696c4f83a2ca7edd02edeab3479c41f4cec46887cd3fbb1b278572da54a54235a4c906f65dbb8d2d0bd291ff435191a0",
          "sha256": "d1a913eda4ffca9ccf74ad426117dd89d09ec3cd55ba9d31e834bc0df9794a7b",
          "sha1": "fe7b8fb761c8d4c3fe00199b3380fedb4a452884",
          "md5": "425ae755fefe5efab7dcd56f2ac464eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "requires": "3.0.14"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.9.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.14"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.15"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.7"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ForgeGradle-6.0.0.jar",
          "url": "ForgeGradle-6.0.0.jar",
          "size": 500007,
          "sha512": "46f804eab2df94f43c0e2480e43a0186696c4f83a2ca7edd02edeab3479c41f4cec46887cd3fbb1b278572da54a54235a4c906f65dbb8d2d0bd291ff435191a0",
          "sha256": "d1a913eda4ffca9ccf74ad426117dd89d09ec3cd55ba9d31e834bc0df9794a7b",
          "sha1": "fe7b8fb761c8d4c3fe00199b3380fedb4a452884",
          "md5": "425ae755fefe5efab7dcd56f2ac464eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeGradle-6.0.0-sources.jar",
          "url": "ForgeGradle-6.0.0-sources.jar",
          "size": 219799,
          "sha512": "2ca3ff413c51ff19d5c2820502c1f3328214e0a0fd1c6e77823407ed492839fcd2a147e686270ceabf665d4fe1ac37326de956d18aad8c2a2b3e95013dc2f82f",
          "sha256": "bb662b00db01c57c852b3534772c79d952491c73af3e37c5994bc23947f2b584",
          "sha1": "e076b47d6005e988f0e29539186b857629fcfa64",
          "md5": "a7103654e0bad342d8d80270a2fc50dc"
        }
      ]
    }
  ]
}
