{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "propatcher",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "propatcher-1.4.0.jar",
          "url": "propatcher-1.4.0.jar",
          "size": 52228,
          "sha512": "14496927ba6d62f62a135a881af5d5d09f8a5b21960fff9f2faec6ccd24fcc820938741495d056bc856dbb8d5d2b90602017a7ae6e6ad77e5e4491f1fd7bda88",
          "sha256": "9a53734d30c3746eb7329de81f442abce6efacf3f6f9facebdadb94741715c76",
          "sha1": "7804264c88a87c3b43e58babd6dd670552627f5d",
          "md5": "9481ed7f1d83936520d9b99c629599c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.cloudbees",
          "module": "diff4j",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "propatcher-1.4.0.jar",
          "url": "propatcher-1.4.0.jar",
          "size": 52228,
          "sha512": "14496927ba6d62f62a135a881af5d5d09f8a5b21960fff9f2faec6ccd24fcc820938741495d056bc856dbb8d5d2b90602017a7ae6e6ad77e5e4491f1fd7bda88",
          "sha256": "9a53734d30c3746eb7329de81f442abce6efacf3f6f9facebdadb94741715c76",
          "sha1": "7804264c88a87c3b43e58babd6dd670552627f5d",
          "md5": "9481ed7f1d83936520d9b99c629599c5"
        }
      ]
    }
  ]
}
